image:
  - Visual Studio 2017

platform:
  - x64

configuration:
  - Debug

build_script:
- mkdir build
- cd build
- cmake c:/projects/CityGen -G "Ninja"
- cmake --build . -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake

install:
- cd c:/tools/vcpkg
- vcpkg integrate install
- vcpkg install catch2 sfml

cache: c:/tools/vcpkg/installed/
