image:
  - Visual Studio 2017

platform:
  - x64

configuration:
  - Debug

environment:
  BOOST_ROOT: c:/libraries/boost_1_68_0

build_script:
- mkdir build
- cd build
- cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake c:/projects/CityGen -DBOOST_ROOT="%BOOST_ROOT%" -G "Visual Studio 15"
- cmake --build .

install:
#- cd c:/tools/vcpkg
#- vcpkg integrate install
#- vcpkg install catch2 sfml

cache: c:/tools/vcpkg/installed/

notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
